name: MineBlock
version: '${version}'
main: fr.farmeurimmo.mineblock.purpur.MineBlock
api-version: '1.18'
author: Mine
description: Mine skyblock plugin
website: https://mine.fr
depend:
  - SlimeWorldManager
commands:
  buildspawn:
    description: Permet de modifier le spawn (déconseillé il faut modifier la template)
    permission: mineblock.buildspawn
  featherfly:
    description: Donne des plumes de fly temporaire
    permission: mineblock.featherfly
  money:
    description: Montre l'argent du joueur
  is:
    description: Permet d'accéder aux commandes de l'île
    aliases:
      - ile
  chests:
    permission: mineblock.chests
  minions:
    permission: mineblock.minions
  trade:
    permission: mineblock.trade
  tradeaccept:
  tradedeny:
  tradecancel:
  spawn:
  shop:
  sellall:
    permission: mineblock.sellall
  trash:
  craft:
    permission: mineblock.craft
  enchantement:
    permission: mineblock.enchantement
  anvil:
    permission: mineblock.anvil
  furnace:
    permission: mineblock.furnace
  silo:
    permission: mineblock.silo
  feed:
    permission: mineblock.feed
  near:
    permission: mineblock.near
  fix:
    permission: mineblock.fix
  kits:
  tpa:
  tpayes:
  tpadeny:
