name: SkylyBlock
version: '${version}'
main: fr.farmeurimmo.skylyblock.purpur.SkylyBlock
api-version: '1.18'
author: Skyly
description: Skyly skyblock plugin
website: https://skyly.fr
depend:
  - SlimeWorldManager
commands:
  buildspawn:
    description: Permet de modifier le spawn (déconseillé il faut modifier la template)
    permission: skylyblock.buildspawn
  featherfly:
    description: Donne des plumes de fly temporaire
    permission: skylyblock.featherfly
  money:
    description: Montre l'argent du joueur
  is:
    description: Permet d'accéder aux commandes de l'île
    aliases:
      - island
      - ile
  chests:
    permission: skylyblock.chests
  minions:
    permission: skylyblock.minions
  trade:
    permission: skylyblock.trade
  tradeaccept:
  tradedeny:
  tradecancel:
  spawn:
  shop: